version: '3.8'

services:
  data-importer:
    build:
      context: ./app
    container_name: linky-data-importer
    environment:
      - MQTT_HOST=192.168.0.10
      - MQTT_PORT=1883
      - VM_HOST=192.168.0.10
    restart: always

