

services:
  data-importer:
    image: pbranly/linkycreationdockermqtt:latest
    container_name: linky-multi-db
    environment:
      # Fuseau horaire
      - TZ=Europe/Paris               # Fuseau horaire pour datetime et calculs journaliers
      # MQTT Configuration
      - LOGIN=${MQTT_USERNAME:-}
      - PASSWORD=${MQTT_PASSWORD:-}
      - MQTT_HOST=${MQTT_HOST:-192.168.0.10}
      - MQTT_PORT=${MQTT_PORT:-1883}
      
      # Database Type Selection (victoriametrics or influxdb)
      - DB_TYPE=${DB_TYPE:-victoriametrics}
      
      # VictoriaMetrics Configuration (used if DB_TYPE=victoriametrics)
      - VM_HOST=${VM_HOST:-192.168.0.10}
      - VM_PORT=${VM_PORT:-8428}
      
      # InfluxDB v2 Configuration (used if DB_TYPE=influxdb)
      - INFLUXDB_URL=${INFLUXDB_URL:-http://192.168.0.10:8086}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-homeassistant}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-homeassistant}
      

      # Intervalle de publication MQTT
      - PUBLISH_INTERVAL=300          # Intervalle entre chaque envoi JSON complet (en secondes, ici 5 min)
      
      
      # définition du nom du sensor. Par défaut linky_tic
      - SENSOR_NAME=linky_tic   # <--- paramétrable ici

      # Debug / Logging
      - DEBUG=true                   # Optionnel: true pour logs détaillés ( non fonctionnel)

    restart: always
    command: ["python", "-u", "main.py"]  # mode unbuffered pour logs en temps réel
    tty: false


